name: climate-tracker
services:
  web-nuxt:
    build: ./web-nuxt
    container_name: climate-web-nuxt
    restart: always
    networks:
      - default
    ports:
      - 9050:3000
    depends_on:
      - api
    develop:
      watch:
        - action: rebuild
          path: ./web-nuxt
    environment:
      - NUXT_PUBLIC_API_BASE_URL=https://api:3000
  web:
    build: ./web
    container_name: climate-web
    restart: always
    networks:
      - default
    ports:
      - 80:80
    depends_on:
      - api
    develop:
      watch:
        - action: sync
          path: ./web/src
          target: ./usr/share/nginx/html
  db:
    build: ./db
    container_name: climate-db
    restart: always
    networks:
      - default
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=secret
      - MONGO_INITDB_DATABASE=mydb
    ports:
      - 9052:27017
    volumes:
      # - /home/vazy/ClimateTracker/db:/data/db
      - ./db/data:/data/db
  api:
    build: ./api
    container_name: climate-api
    restart: always
    networks:
      - default
    ports:
      - 9051:3000
    depends_on:
      - db
    develop:
      watch:
        - action: rebuild
          path: "./api"
networks:
  default:
    name: climate-tracker
