/**
 * Climate API
 * API for the Climate project.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The AddSensorPost200Response model module.
 * @module model/AddSensorPost200Response
 * @version 0.1.0
 */
class AddSensorPost200Response {
    /**
     * Constructs a new <code>AddSensorPost200Response</code>.
     * Sensor successfully added.
     * @alias module:model/AddSensorPost200Response
     */
    constructor() { 
        
        AddSensorPost200Response.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>AddSensorPost200Response</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AddSensorPost200Response} obj Optional instance to populate.
     * @return {module:model/AddSensorPost200Response} The populated <code>AddSensorPost200Response</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AddSensorPost200Response();

            if (data.hasOwnProperty('insertedId')) {
                obj['insertedId'] = ApiClient.convertToType(data['insertedId'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>AddSensorPost200Response</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>AddSensorPost200Response</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['insertedId'] && !(typeof data['insertedId'] === 'string' || data['insertedId'] instanceof String)) {
            throw new Error("Expected the field `insertedId` to be a primitive type in the JSON string but got " + data['insertedId']);
        }

        return true;
    }


}



/**
 * @member {String} insertedId
 */
AddSensorPost200Response.prototype['insertedId'] = undefined;






export default AddSensorPost200Response;

