/**
 * Climate API
 * API for the Climate project.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The AllReadingsGet200ResponseInner model module.
 * @module model/AllReadingsGet200ResponseInner
 * @version 0.1.0
 */
class AllReadingsGet200ResponseInner {
    /**
     * Constructs a new <code>AllReadingsGet200ResponseInner</code>.
     * @alias module:model/AllReadingsGet200ResponseInner
     */
    constructor() { 
        
        AllReadingsGet200ResponseInner.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>AllReadingsGet200ResponseInner</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AllReadingsGet200ResponseInner} obj Optional instance to populate.
     * @return {module:model/AllReadingsGet200ResponseInner} The populated <code>AllReadingsGet200ResponseInner</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AllReadingsGet200ResponseInner();

            if (data.hasOwnProperty('sensorID')) {
                obj['sensorID'] = ApiClient.convertToType(data['sensorID'], 'String');
            }
            if (data.hasOwnProperty('temperature')) {
                obj['temperature'] = ApiClient.convertToType(data['temperature'], 'Number');
            }
            if (data.hasOwnProperty('humidity')) {
                obj['humidity'] = ApiClient.convertToType(data['humidity'], 'Number');
            }
            if (data.hasOwnProperty('timestamp')) {
                obj['timestamp'] = ApiClient.convertToType(data['timestamp'], 'Date');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>AllReadingsGet200ResponseInner</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>AllReadingsGet200ResponseInner</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['sensorID'] && !(typeof data['sensorID'] === 'string' || data['sensorID'] instanceof String)) {
            throw new Error("Expected the field `sensorID` to be a primitive type in the JSON string but got " + data['sensorID']);
        }

        return true;
    }


}



/**
 * @member {String} sensorID
 */
AllReadingsGet200ResponseInner.prototype['sensorID'] = undefined;

/**
 * @member {Number} temperature
 */
AllReadingsGet200ResponseInner.prototype['temperature'] = undefined;

/**
 * @member {Number} humidity
 */
AllReadingsGet200ResponseInner.prototype['humidity'] = undefined;

/**
 * @member {Date} timestamp
 */
AllReadingsGet200ResponseInner.prototype['timestamp'] = undefined;






export default AllReadingsGet200ResponseInner;

