/**
 * Climate API
 * API for the Climate project.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The SensorPatch200Response model module.
 * @module model/SensorPatch200Response
 * @version 0.1.0
 */
class SensorPatch200Response {
    /**
     * Constructs a new <code>SensorPatch200Response</code>.
     * Sensor successfully updated.
     * @alias module:model/SensorPatch200Response
     */
    constructor() { 
        
        SensorPatch200Response.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>SensorPatch200Response</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SensorPatch200Response} obj Optional instance to populate.
     * @return {module:model/SensorPatch200Response} The populated <code>SensorPatch200Response</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SensorPatch200Response();

            if (data.hasOwnProperty('modifiedCount')) {
                obj['modifiedCount'] = ApiClient.convertToType(data['modifiedCount'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>SensorPatch200Response</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>SensorPatch200Response</code>.
     */
    static validateJSON(data) {

        return true;
    }


}



/**
 * @member {Number} modifiedCount
 */
SensorPatch200Response.prototype['modifiedCount'] = undefined;






export default SensorPatch200Response;

