version: '3'
services:
  web:
    labels: 
        com.example.description: "ClimateTracker - Web"
    build: ./web
    ports:
      - 8080:80
    depends_on:
      - db
      - api

  db:
    labels: 
      com.example.description: "ClimateTracker - DB"
    image: arm64v8/mongo:4.4.8
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=secret
      - MONGO_INITDB_DATABASE=mydb
    ports:
      - 8082:27017

  api:
    labels: 
      com.example.description: "ClimateTracker - API"
    build: ./api
    ports:
      - 8081:3000
    depends_on:
      - db
