version: '3'
services:
  web:
    build: ./web
    ports:
      - 8080:80
    depends_on:
      - db
      - api

  db:
    image: arm64v8/mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=secret
      - MONGO_INITDB_DATABASE=mydb
    ports:
      - 8082:27017

  api:
    build: ./api
    ports:
      - 8081:3000
    depends_on:
      - db
