version: '3'
name: climate-tracker
services:
  web:
    build: ./web
    container_name: web
    networks:
      - default
    ports:
      - 80:80
    depends_on:
      - db
      - api
    develop:
      watch:
        - action: sync
          service: web
          path: ./web/src
          target: ./usr/share/nginx/html
  db:
    build: ./db
    container_name: db
    networks:
      - default
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=secret
      - MONGO_INITDB_DATABASE=mydb
    ports:
      - 9052:27017
    volumes:
      - /home/vazy/ClimateTracker/db:/data/db
  api:
    build: ./api
    container_name: api
    networks:
      - default
    ports:
      - 9051:3000
    depends_on:
      - db
    develop:
      watch:
        - action: rebuild
          path: "./api"
networks:
  default:
    name: climate-tracker
