version: '3'
services:
  web:
    build: ./web
    ports:
      - 80:80
    depends_on:
      - db
      - api

  db:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=secret
      - MONGO_INITDB_DATABASE=mydb

  api:
    build: ./api
    ports:
      - 8080:8080
    depends_on:
      - db
