name: Deploy website to pi
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and run docker image
    runs-on: self-hosted
    environment: prod
    defaults:
      run:
        working-directory: ./PI
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run docker build
        run: sudo docker build -t climatetracker .
      
      - name: Stop docker container
        run: sudo docker stop climatetracker || true

      - name: Start docker container
        run: sudo docker run -d --rm -p 8080:80 --name climatetracker climatetracker --restart unless-stopped