name: Deploy website to pi
on:
  push:
    branches:
      - main

jobs:
  stop:
    name: Stop existing docker containers
    runs-on: self-hosted
    steps:
      - name: Stop docker containers
        run: sudo docker-compose down || true

  build_and_start:
    name: Build and start docker containers
    needs: stop
    runs-on: self-hosted
    defaults:
      run:
        working-directory: ./pi
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build and start docker containers
        run: sudo docker-compose up --build -d
      