name: Deploy website to pi
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build docker image
    runs-on: self-hosted
    environment: prod
    defaults:
      run:
        working-directory: ./PI
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run docker build
        run: sudo docker build -t climatetracker .

  stop:
    name: Stop and remove docker container
    needs: build
    runs-on: self-hosted
    steps:
      - name: Stop docker container
        run: sudo docker stop climatetracker || true

      - name: Remove docker container
        run: sudo docker rm climatetracker || true

  start:
    name: Start docker container
    needs: stop
    runs-on: self-hosted
    steps:
      - name: Start docker container
        run: sudo docker run -d --restart unless-stopped -p 8080:80 --name climatetracker climatetracker